[project]
name = "chemprop-mods"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chemprop==2.2.0",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "openpyxl>=3.1.5",
    "pandas==2.3",
    "tyro>=1.0.8",
    "wandb>=0.27.0",
]
